# Detached Thread Demo Makefile
CXX		 = g++
CXXFLAGS = -Wall -std=c++11
TARGET	 = detached_thread_demo
SRC		 = *.exe

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) $(SRC) -o $(TARGET)


clean:
	rm -f $(TARGET)